# Generated by Django 3.1.3 on 2020-12-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=1000)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('interest', models.CharField(max_length=122)),
                ('instagram_link', models.CharField(max_length=122)),
            ],
        ),
    ]
