# Generated by Django 3.1.3 on 2020-12-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0002_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='user_name',
            field=models.CharField(default=1, max_length=122),
            preserve_default=False,
        ),
    ]
