# Generated by Django 3.1.1 on 2020-12-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0003_bio_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='image',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
