# Generated by Django 3.1.1 on 2020-12-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0004_bio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='image',
            field=models.ImageField(upload_to='../static/images'),
        ),
    ]
