# Generated by Django 3.1.1 on 2020-12-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0005_auto_20201223_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
