# Generated by Django 3.1.1 on 2020-12-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0006_auto_20201223_0157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='', upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='bio',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
