# Generated by Django 3.1.1 on 2020-12-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0007_auto_20201224_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='user_name',
            field=models.CharField(default='', max_length=122),
        ),
    ]
