# Generated by Django 3.1.1 on 2020-12-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0008_photos_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.ImageField(default='', upload_to='upload_photo'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='user_name',
            field=models.CharField(max_length=122),
        ),
    ]
